### ISSUE TITLE
Add info to footer

### ISSUE THREAD

**Issue by soggybag** [soggybag/tetris-redux-app#7]
The footer is largely unused. Might be a good place for information. Here are a few things that can go in the footer.

  - Links 
    - Info on Tetris and history of Tetris
    - Link to source tutorial
    - Links to React and Redux
    - Link to this GitHub Repo
    - Links to issues for this Repo
- Links to Collaborators on this project

Approach: Might be good to create a footer component. Currently all of the styles for the project are in `src/index.css`.

**Comment by ryanlsmith4** [comment]
This appears to already be completed.

**Comment by soggybag** [comment]
Closed, thanks!
