### ISSUE TITLE
Style and UX improvements

### ISSUE THREAD

**Issue by soggybag** [soggybag/tetris-redux-app#8]
Currently the text on the buttons can be selected when you click and drag. This is not good UI. It can be fixed with some CSS styles.

- https://developer.mozilla.org/en-US/docs/Web/CSS/user-select

All of the styles are in `src/index.css`. 

Identify the things that do not need to be selected and make them unelectable with `user-select`. This is probably everything in game: buttons, grid, and squares. The footer and header should probably remain selectable.

**Comment by thadia** [comment]
https://github.com/soggybag/tetris-redux-app/pull/10

**Comment by soggybag** [comment]
I created these issues for my students to practice with. I explained the assignment this afternoon. Half way through class I saw your pull request!

**Comment by thadia** [comment]
I was participating at an workshop about open source and this recently created issue was listed first in my quick search for an easy bug. Sorry!!

**Comment by soggybag** [comment]
It’s not a problem at all. I mentioned it to the class after the break. I pointed out they would have to get on the issues or they would all be gone.

**Comment by soggybag** [comment]
Closed, thanks!
